name: Deploy .NET Application

on:
  push:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  build:

    runs-on: self-hosted  

    env:
      Solution_Name: TSP.sln                         
      Project_Path: TSP.WPF/TSP.WPF.csproj                

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - run: dotnet restore ${{ env.Project_Path }}

    - run: dotnet build ${{ env.Project_Path }} -c Release --no-restore

    - run: dotnet publish ${{ env.Project_Path }} -c Release --self-contained -r win-arm64
